
------------------- TABLAS DEL PROYECTO --------
SELECT * FROM ROLES;
SELECT * FROM USUARIOS;
SELECT * FROM CLIENTES;
SELECT * FROM CHOFERES;
SELECT * FROM PAGOS_DIARIOS;
SELECT * FROM REGISTROS_VALORES;
SELECT * FROM CARRERAS;
SELECT * FROM PROMOCIONES;
SELECT * FROM DETALLES_PROMOCIONES;

DELETE FROM CARRERAS;
DELETE FROM CHOFERES;
DELETE FROM CLIENTES;
DELETE FROM PAGOS_DIARIOS;
DELETE FROM REGISTROS_VALORES;
DELETE FROM PROMOCIONES;
DELETE FROM DETALLES_PROMOCIONES;
