---------------------------------------------------------------CREACIONES DE TABLAS PROYECTO COOPERATIVA TAXI FASTCAR ---------------------------
--TABLA ROLES ---
CREATE TABLE ROLES(
ID     NUMBER,
ROL    VARCHAR2(30),
ESTADO VARCHAR2(2)
);
----- primary key---
alter table ROLES
  add constraint PK_ID_ROLES primary key (ID)

---- TABLA USUARIOS ---
CREATE TABLE USUARIOS(
ID NUMBER,
CEDULA VARCHAR2(15) NOT NULL,
NOMBRES      VARCHAR2(25) NOT NULL,
APELLIDOS    VARCHAR2(25)NOT NULL,
PASSWORD       VARCHAR2(50)NOT NULL,
FECHA_REGISTRO              DATE NULL,
FECHA_MODIFICACION          DATE NULL,
ID_ROLES                    NUMBER NOT NULL
);
----- PRIMARY KEY---
alter table USUARIOS
  add constraint PK_ID_USUARIOS primary key (CEDULA);
----- FOREING KEY---
alter table USUARIOS
  add constraint FK_ID_ROLES foreign key (ID_ROLES)
  references ROLES (ID);
-- secuencia -------
CREATE SEQUENCE usuarios_id
START WITH 1
INCREMENT BY 1;

----TABLA CLIENTES----
CREATE TABLE CLIENTES(
ID NUMBER,
NOMBRES      VARCHAR2(30) NOT NULL,
APELLIDOS    VARCHAR2(30) NOT NULL,
DIRECCION    VARCHAR2(100) NOT NULL,
TELEFONO     VARCHAR2(10) NOT NULL,
FECHA_REGISTRO              DATE NULL,
FECHA_MODIFICACION          DATE NULL
);
----- PRIMARY KEY---
alter table CLIENTES
  add constraint PK_ID_CLIENTES primary key (TELEFONO)
-- secuencia -------
CREATE SEQUENCE clientes_id
START WITH 1
INCREMENT BY 1;

---TABLA CHOFERES----
CREATE TABLE CHOFERES(
ID NUMBER,
MOVIL  NUMBER,
NOMBRES      VARCHAR2(30) NOT NULL,
APELLIDOS    VARCHAR2(30) NOT NULL,
DIRECCION    VARCHAR2(100)NOT NULL,
TELEFONO     VARCHAR2(10) NOT NULL,
COLOR_VEHICULO           VARCHAR2(25) NOT NULL,
PLACA                    VARCHAR2(20) NOT NULL,
MODELO                   VARCHAR2(30) NOT NULL,
ESTADO                   VARCHAR2(2)  DEFAULT 'A',
FECHA_REGISTRO              DATE NULL,
FECHA_MODIFICACION          DATE NULL
)
----- PRIMARY KEY---
alter table CHOFERES
  add constraint PK_ID_CHOFERES primary key (MOVIL)
-- secuencia -------
CREATE SEQUENCE choferes_id
START WITH 1
INCREMENT BY 1;

--TABLA PAGOS_DIARIOS---
CREATE TABLE PAGOS_DIARIOS(
ID NUMBER,
MOVIL  NUMBER,
FECHA_REGISTRO VARCHAR2(20),
VALOR          NUMBER(4,2)
)
----- PRIMARY KEY---
alter table PAGOS_DIARIOS
  add constraint PK_ID_PAGOS_DIARIOS primary key (ID);
---FOREIGN KEY----
alter table PAGOS_DIARIOS
  add constraint FK_ID_CHOFERES foreign key (MOVIL)
  references CHOFERES (MOVIL);
-- secuencia -------
CREATE SEQUENCE pagos_diarios_id
START WITH 1
INCREMENT BY 1;

---- TABLA REGISTROS_VALORES---
CREATE TABLE REGISTROS_VALORES(
ID NUMBER,
ORIGEN VARCHAR2(100)NOT NULL,
DESTINO     VARCHAR2(100)NOT NULL,
VALOR       NUMBER(4,2) NOT NULL,
FECHA_REGISTRO              DATE NULL,
FECHA_MODIFICACION          DATE NULL
);
----- PRIMARY KEY---
alter table REGISTROS_VALORES
  add constraint PK_ID_REGISTROS_VALORES primary key (ORIGEN,DESTINO);
-- secuencia -------
CREATE SEQUENCE registros_valores_id
START WITH 1
INCREMENT BY 1;

--- TABLA CARRERAS ----
CREATE TABLE CARRERAS(
ID NUMBER,
CLIENTE      VARCHAR2(60),
REFERENCIA   VARCHAR2(150),
ORIGEN       VARCHAR2(100),
DESTINO     VARCHAR2(100),
TELEFONO    VARCHAR2(10),
VALOR       NUMBER(4,2),
MOVIL       NUMBER,
FECHA_HORA_REGISTRO DATE NULL
);
----- PRIMARY KEY---
alter table CARRERAS
  add constraint PK_ID_CARRERAS primary key (ID);
---FOREIGN KEY----
alter table CARRERAS
  add constraint FK_ID_CLIENTES foreign key (TELEFONO)
  references CLIENTES (TELEFONO);
/*alter table CARRERAS
  add constraint FK_ID_REGISTROS_VALORES foreign key (ORIGEN,DESTINO)
  references REGISTROS_VALORES (ORIGEN,DESTINO);*/
alter table CARRERAS
  add constraint FK_ID_CHOFERES_CARRERAS foreign key (MOVIL)
  references CHOFERES (MOVIL);
-- secuencia -------
CREATE SEQUENCE CARRERAS_id
START WITH 1
INCREMENT BY 1;


---TABLA PROMOCIONES--
CREATE TABLE PROMOCIONES(
ID NUMBER,
DESCRIPCION VARCHAR2(1000),
ESTADO       VARCHAR2(1)DEFAULT 'A',
FECHA_INICIO DATE,
FECHA_FIN DATE
);
----- PRIMARY KEY---
alter table PROMOCIONES
  add constraint PK_ID_PROMOCIONES primary key (ID);
-- secuencia -------
CREATE SEQUENCE PROMOCIONES_id
START WITH 1
INCREMENT BY 1;

--TABLA DETALLE_PROMOCIONES--
CREATE TABLE DETALLES_PROMOCIONES(
ID NUMBER,
TELEFONO_CLIENTE         VARCHAR2(10),
NUMERO_SORTEO   NUMBER,
FECHA_REGISTRO  DATE,
ID_PROMOCION    NUMBER,
ID_MOVIL        NUMBER   
);
alter table DETALLES_PROMOCIONES
  add constraint PK_ID_DETALLES_PROMOCIONES primary key (ID);

alter table DETALLES_PROMOCIONES
  add constraint FK_ID_CHOFERES_PROMOCINES foreign key (ID_MOVIL)
  references CHOFERES (MOVIL);
  
alter table DETALLES_PROMOCIONES
  add constraint FK_ID_DETALLE_PROMOCINES foreign key (ID_PROMOCION)
  references PROMOCIONES (ID);
  
alter table DETALLES_PROMOCIONES
  add constraint FK_ID_CLIENTES_PROMOCINES foreign key (TELEFONO_CLIENTE)
  references CLIENTES (TELEFONO);

CREATE SEQUENCE DETALLES_PROMOCIONES_id
START WITH 1
INCREMENT BY 1;






