SELECT COUNT(*) FROM USUARIOS WHERE CEDULA='0929596708' AND PASSWORD='12345';

insert into roles
  (id, rol, estado)
values
  (2, 'Operadoras', 'A');
  

insert into usuarios
  (id, cedula, nombres, apellidos, password, fecha_registro, fecha_modificacion, id_roles)
values
  (usuarios_id.nextval, '0929596708', 'JOHN ENRIQUE', 'CARDOZO VILLON', '12345678', SYSDATE, SYSDATE, 1);
  
  
SELECT ROL FROM ROLES;


SELECT * FROM USUARIOS WHERE CEDULA='0929596708';

UPDATE USUARIOS SET PASSWORD=(?), FECHA_MODIFICACION=SYSDATE,ID_ROLES =(?) WHERE CEDULA=(?);


INSERT INTO CHOFERES (ID, MOVIL, NOMBRES, APELLIDOS, DIRECCION, TELEFONO, COLOR_VEHICULO, PLACA, MODELO, ESTADO, FECHA_REGISTRO, FECHA_MODIFICACION) VALUES (choferes_id.nextval, (?), UPPER(?), UPPER(?), UPPER(?), (?), UPPER(?), UPPER(?), UPPER(?), SYSDATE, NULL);


SELECT COUNT(*) CANTIDAD FROM CHOFERES WHERE MOVIL = 37;

DELETE FROM CHOFERES;

SELECT * FROM CHOFERES A WHERE MOVIL = 37;

UPDATE CHOFERES SET DIRECCION = (?), TELEFONO = (?), COLOR_VEHICULO = (?), PLACA = (?), MODELO = (?), FECHA_MODIFICACION = SYSDATE WHERE MOVIL = (?);

INSERT INTO PAGOS_DIARIOS (ID, MOVIL, FECHA_REGISTRO, VALOR) VALUES (3, 37, '04/10/2016', 10.20);

DELETE FROM PAGOS_DIARIOS WHERE ID =14;

SELECT COUNT(*) CANTIDAD FROM PAGOS_DIARIOS WHERE FECHA_REGISTRO=(?) AND MOVIL = (?);

INSERT INTO REGISTROS_VALORES (ID, ORIGEN, DESTINO, VALOR, FECHA_REGISTRO, FECHA_MODIFICACION) VALUES (registros_valores_id.nextval, UPPER('22 y maldonado'), UPPER('mall del sur'), 3.50, sysdate, null);

SELECT COUNT(*) CANTIDAD FROM REGISTROS_VALORES WHERE ORIGEN=UPPER(?) AND DESTINO=UPPER(?)

DELETE FROM REGISTROS_VALORES;

SELECT COUNT(*) CANTIDAD FROM PROMOCIONES WHERE ESTADO='A';

insert into promociones (id, descripcion, fecha_inicio, fecha_fin) values (PROMOCIONES_id.Nextval, UPPER(?), SYSDATE, NULL);

update promociones set id = estado = v_estado, fecha_fin = sysdate;

SELECT COUNT(*) CANTIDAD FROM CLIENTES WHERE TELEFONO ='0990200782';

SELECT ORIGEN,DESTINO FROM REGISTROS_VALORES;

SELECT TO_CHAR(VALOR) FROM REGISTROS_VALORES;

SELECT COUNT(*) FROM PAGOS_DIARIOS WHERE TO_DATE(FECHA_REGISTRO,'DD/MM/YYYY')>= TO_DATE(SYSDATE,'DD/MM/RRRR')-2 AND MOVIL = 37;

INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, DIRECCION, TELEFONO, FECHA_REGISTRO, FECHA_MODIFICACION) VALUES (clientes_id.nextval, (?), (?), (?), (?), SYSDATE, NULL);

INSERT INTO CARRERAS (ID, CLIENTE, REFERENCIA, ORIGEN, DESTINO, TELEFONO, VALOR, MOVIL, FECHA_REGISTRO, FECHA_MODIFICACION) VALUES (CARRERAS_id.Nextval, UPPER(?), UPPER(?), UPPER(?), UPPER(?), (?), (?), (?), (?), NULL);

INSERT INTO CARRERAS (ID, CLIENTE, REFERENCIA, ORIGEN, DESTINO, TELEFONO, VALOR, MOVIL, FECHA_HORA_REGISTRO) VALUES (CARRERAS_id.Nextval, UPPER('JOHN ENRIQUE CARDOZO VILLON'), UPPER('FRENTE A VULCANIZADORA S.A'), UPPER('MALDONADO Y LA 22'), UPPER('MALL DEL SOL'), ('0990200782'), (3.50), (37), to_date('03/11/2016 17:17:45','dd/mm/yyyy hh24:mi:ss'));

DELETE FROM CLIENTES;




SELECT CL.NOMBRES,
       CL.APELLIDOS,
       CA.ORIGEN,
       CA.REFERENCIA,
       CA.DESTINO,
       CA.VALOR
  FROM CARRERAS CA, CLIENTES CL
 WHERE CA.FECHA_HORA_REGISTRO =
       (SELECT MAX(FECHA_HORA_REGISTRO)
          FROM CARRERAS
         WHERE TELEFONO = '0990200782')
   AND CA.TELEFONO = '0990200782'
   AND CA.TELEFONO = CL.TELEFONO;
   
   SELECT DISTINCT(ORIGEN) ORIGEN FROM REGISTROS_VALORES

SELECT MAX(NUMERO_SORTEO) FROM DETALLES_PROMOCIONES WHERE ID_PROMOCION = 5;


insert into detalles_promociones (id, cliente, numero_sorteo, fecha_registro, id_promocion, id_movil) values (DETALLES_PROMOCIONES_id.Nextval, UPPER('JOHN ENRIQUE CARDOZO VILLON'), ('0001'), SYSDATE, 37, 5);

